In [1]:
import numpy as np
from sklearn.decomposition import PCA
from tqdm import tqdm
from scipy.linalg import svd

In [2]:
a = np.array([
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
    [1, 1, 0],
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 1]
])

a += [1, 1, 1]

pca = PCA(n_components=1, svd_solver='full', random_state=5, )
pca.fit(a).singular_values_

array([1.41421356])

Судя по всему, PCA из sklearn предварительно центрирует матрицу.

In [3]:
U, S, VT = svd(a - [1.5, 1.5, 1.5], full_matrices=False)

In [4]:
print(U.shape, S.shape, VT.shape, sep='\n')

(8, 3)
(3,)
(3, 3)


In [5]:
U

array([[-0.35355339, -0.35355339, -0.35355339],
       [-0.35355339,  0.35355339, -0.35355339],
       [-0.35355339, -0.35355339,  0.35355339],
       [ 0.35355339, -0.35355339, -0.35355339],
       [ 0.35355339, -0.35355339,  0.35355339],
       [ 0.35355339,  0.35355339, -0.35355339],
       [-0.35355339,  0.35355339,  0.35355339],
       [ 0.35355339,  0.35355339,  0.35355339]])

In [6]:
S

array([1.41421356, 1.41421356, 1.41421356])

Итого мы имеет три равнозначных компоненты. Так как от нас хотят общее число направлений, то мы прибавляем ещё и противоположно направленные векторы. Итого 6 направлений.