In [49]:
import numpy as np

In [50]:
def apply_filter(image, filter):
    res = np.array([
        [0, 0],
        [0, 0]
    ])
    for i in [0, 1]:
        for j in [0, 1]:
            res[i, j] = np.sum(image[i:i + 2, j:j + 2] * filter)
    return res

def apply_max_pool(image):
    return np.amax(image)

In [51]:
images = [
    np.array([[1, 2, 3], [3, 4, 1], [2, 1, 3]]),
    np.array([[1, 1, 2], [2, 6, 1], [0, 1, 2]]),
    np.array([[2, 2, 1], [2, 4, 3], [1, 2, 4]]),
]

filters = [
    np.array([[1, 1], [1, 1]]),
    np.array([[1, 0], [0, 1]]),
    np.array([[0, 1], [0, 1]]),
    np.array([[0, 1], [1, 0]]),
]


In [52]:
classes = np.array([1, 2, 1])
for filter in filters:
    results = []
    for image in images:
        filtered = apply_filter(image, filter)
        pooled = apply_max_pool(filtered)
        results.append(pooled)

    results = np.array(results)
    ids = results.argsort()
    display(classes[ids])

array([1, 2, 1])

array([1, 2, 1])

array([1, 2, 1])

array([1, 1, 2])

Линейно разделимый случай только при применении последнего фильтра.